import json
import os

with open("vsgnn.ipynb", "r") as f:
    nb = json.load(f)

# -----------------------------------------------------------------------------
# Cell 0: Markdown instructions for Colab & Local
# -----------------------------------------------------------------------------
nb["cells"][1]["source"] = [
    "---\n",
    "## 0. Kernel Selection & Automated Dependency Bootstrap\n",
    "\n",
    "> **Execution Environments Supported:**\n",
    "> - **VS Code / Local Jupyter:** Select kernel **`Python (VS-HGNN venv)`** (top-right selector).\n",
    "> - **Google Colab / Cloud VM / Docker:** Run the bootstrap cell below. It automatically checks and installs all missing packages (`torch-geometric`, `scikit-learn`, `networkx`, `seaborn`).\n",
    "> - **Self-Contained Data Pipeline:** Every cell automatically checks if data artifacts (`data/merged/`, `data/graph/`, `data/models/`) exist; if not, it automatically streams raw data and constructs the graph on-the-fly!\n"
]

# -----------------------------------------------------------------------------
# Cell 2: Dependency Bootstrap & Directory Alignment
# -----------------------------------------------------------------------------
nb["cells"][2]["source"] = [
    "# Automated dependency bootstrap for Google Colab and clean environments\n",
    "import os\n",
    "import sys\n",
    "import subprocess\n",
    "\n",
    "# Auto-detect local workspace directory if launched from another path\n",
    "local_dir = '/Users/hamisulawal/Documents/VS-HGNN'\n",
    "if os.path.exists(local_dir) and os.getcwd() != local_dir:\n",
    "    os.chdir(local_dir)\n",
    "    print(f'Aligned working directory to workspace: {local_dir}')\n",
    "\n",
    "required_packages = ['torch', 'torch_geometric', 'scikit-learn', 'networkx', 'seaborn']\n",
    "missing_packages = []\n",
    "\n",
    "for pkg in required_packages:\n",
    "    try:\n",
    "        __import__(pkg)\n",
    "    except ImportError:\n",
    "        missing_packages.append('torch-geometric' if pkg == 'torch_geometric' else 'scikit-learn' if pkg == 'scikit-learn' else pkg)\n",
    "\n",
    "if missing_packages:\n",
    "    print(f'Installing missing dependencies in active kernel: {missing_packages}...')\n",
    "    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q'] + missing_packages)\n",
    "    print('All required dependencies installed successfully!')\n",
    "else:\n",
    "    print('All required dependencies (torch, torch-geometric, scikit-learn, networkx) are ready!')\n",
    "\n",
    "# Ensure project folder structure exists\n",
    "for d in ['data/merged', 'data/graph', 'data/models']:\n",
    "    os.makedirs(d, exist_ok=True)\n"
]

# -----------------------------------------------------------------------------
# Cell 7: Step 1 Ingestion & Hash-Join (Self-Contained)
# -----------------------------------------------------------------------------
nb["cells"][7]["source"] = [
    "import os\n",
    "import io\n",
    "import json\n",
    "import urllib.request\n",
    "import subprocess\n",
    "import zipfile\n",
    "import tarfile\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "benchmark_path = 'data/merged/vs_hgnn_supervised_benchmark.csv'\n",
    "\n",
    "if not os.path.exists(benchmark_path):\n",
    "    print('Local benchmark not found. Streaming raw datasets and executing Step 1 Hash-Join...')\n",
    "    os.makedirs('data/merged', exist_ok=True)\n",
    "    \n",
    "    # 1. Stream DIVE Addresses & Ground-Truth Labels\n",
    "    print('[1/3] Fetching DIVE addresses and multi-label ground truth...')\n",
    "    dive_sc_url = 'https://raw.githubusercontent.com/DIVE4Data/DIVE/main/RawData/SC_Addresses/SC_Addresses.csv'\n",
    "    df_dive_addr = pd.read_csv(dive_sc_url)\n",
    "    df_dive_addr['contractID'] = df_dive_addr.index + 1\n",
    "    df_dive_addr['norm_address'] = df_dive_addr['contractAddress'].astype(str).str.lower().str.strip()\n",
    "    \n",
    "    zenodo_labels_url = 'https://zenodo.org/api/records/18519253/files/DIVE_Labels.zip/content'\n",
    "    res = subprocess.run(['curl', '-s', '-L', zenodo_labels_url], capture_output=True, check=True)\n",
    "    with zipfile.ZipFile(io.BytesIO(res.stdout)) as z:\n",
    "        df_dive_labels = pd.read_csv(z.open('Labels/DIVE_Labels.csv'))\n",
    "        df_dive_tools = pd.read_csv(z.open('Labels/Tool_Results.csv'))\n",
    "    \n",
    "    df_dive_full = df_dive_addr.merge(df_dive_labels, on='contractID', how='inner')\n",
    "    df_dive_full = df_dive_full.merge(df_dive_tools, on='contractID', how='left')\n",
    "    print(f'      DIVE labeled contracts: {len(df_dive_full):,}')\n",
    "    \n",
    "    # 2. Stream SmartBugs Wild On-Chain Metadata\n",
    "    print('[2/3] Streaming SmartBugs Wild transaction & runtime metadata...')\n",
    "    sb_url = 'https://raw.githubusercontent.com/smartbugs/smartbugs-wild/master/contracts.csv.tar.gz'\n",
    "    req_sb = urllib.request.Request(sb_url, headers={'User-Agent': 'Mozilla/5.0'})\n",
    "    with urllib.request.urlopen(req_sb) as resp:\n",
    "        compressed_sb = resp.read()\n",
    "    with tarfile.open(fileobj=io.BytesIO(compressed_sb), mode='r:gz') as tar:\n",
    "        df_sb = pd.read_csv(tar.extractfile(tar.getmembers()[0]))\n",
    "        \n",
    "    df_sb['norm_address'] = df_sb['address'].astype(str).str.lower().str.strip()\n",
    "    df_sb['nb_transaction'] = pd.to_numeric(df_sb['nb_transaction'], errors='coerce').fillna(0).astype(np.int64)\n",
    "    df_sb['balance'] = pd.to_numeric(df_sb['balance'], errors='coerce').fillna(0)\n",
    "    print(f'      SmartBugs Wild contracts: {len(df_sb):,}')\n",
    "    \n",
    "    # 3. Optimized Hash-Join (Inner Join: Supervised Core)\n",
    "    print('[3/3] Executing exact hash-join across normalized addresses...')\n",
    "    sb_cols = ['norm_address', 'nb_transaction', 'creation_date', 'last_transaction_date', 'compiler_version', 'name', 'balance']\n",
    "    df_merged = df_dive_full.merge(df_sb[sb_cols], on='norm_address', how='inner')\n",
    "    df_merged.drop_duplicates(subset=['norm_address'], inplace=True)\n",
    "    df_merged['has_ground_truth'] = True\n",
    "    df_merged.to_csv(benchmark_path, index=False)\n",
    "    print(f'      Successfully saved Supervised Benchmark to {benchmark_path}!')\n",
    "else:\n",
    "    df_merged = pd.read_csv(benchmark_path)\n",
    "    print(f'Supervised Benchmark Loaded: {len(df_merged):,} rows x {df_merged.shape[1]} columns')\n",
    "\n",
    "df_merged[['contractAddress', 'compiler_version', 'nb_transaction', 'balance', 'Reentrancy', 'Access Control', 'Arithmetic']].head(3)\n"
]

# -----------------------------------------------------------------------------
# Cell 9: Heterogeneous Graph Loading & Construction (Self-Contained)
# -----------------------------------------------------------------------------
nb["cells"][9]["source"] = [
    "# Defensive imports to support running cells independently in any kernel\n",
    "import os\n",
    "import sys\n",
    "import torch\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.neighbors import NearestNeighbors\n",
    "\n",
    "try:\n",
    "    from torch_geometric.data import HeteroData\n",
    "except ImportError:\n",
    "    import subprocess\n",
    "    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', 'torch-geometric'])\n",
    "    from torch_geometric.data import HeteroData\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')\n",
    "graph_path = 'data/graph/vs_hgnn_hetero_graph.pt'\n",
    "\n",
    "if not os.path.exists(graph_path):\n",
    "    print(f'Graph file not found at {graph_path}. Constructing VS-HGNN Heterogeneous Graph on-the-fly...')\n",
    "    os.makedirs('data/graph', exist_ok=True)\n",
    "    \n",
    "    # Ensure benchmark dataset is loaded\n",
    "    benchmark_path = 'data/merged/vs_hgnn_supervised_benchmark.csv'\n",
    "    if 'df_merged' not in locals() or df_merged is None:\n",
    "        df_merged = pd.read_csv(benchmark_path)\n",
    "    df = df_merged.copy()\n",
    "    N = len(df)\n",
    "    \n",
    "    # 1. Feature Engineering: Multi-modal contract node representation\n",
    "    df['log_tx'] = np.log10(pd.to_numeric(df['nb_transaction'], errors='coerce').fillna(0) + 1.0)\n",
    "    df['log_balance'] = np.log10(pd.to_numeric(df['balance'], errors='coerce').fillna(0) + 1.0)\n",
    "    c_date = pd.to_datetime(df['creation_date'], errors='coerce')\n",
    "    l_date = pd.to_datetime(df['last_transaction_date'], errors='coerce')\n",
    "    df['lifecycle_days'] = ((l_date - c_date).dt.total_seconds() / (24 * 3600)).fillna(0).clip(lower=0)\n",
    "    \n",
    "    X_runtime = StandardScaler().fit_transform(df[['log_tx', 'log_balance', 'lifecycle_days']])\n",
    "    tool_cols = [c for c in df.columns if any(t in c for t in ['MAIAN', 'Mythril', 'Semgrep', 'Slither', 'Solhint', 'VeriSmart'])]\n",
    "    X_tools = df[tool_cols].fillna(0).astype(np.float32).values\n",
    "    \n",
    "    top_compilers = df['compiler_version'].value_counts().head(20).index.tolist()\n",
    "    compiler_dummies = pd.get_dummies(df['compiler_version'].apply(lambda x: x if x in top_compilers else 'Other'), prefix='comp')\n",
    "    X_compilers = compiler_dummies.values.astype(np.float32)\n",
    "    X_contracts = np.hstack([X_runtime, X_tools, X_compilers]).astype(np.float32)\n",
    "    \n",
    "    # 2. Multi-label ground truth target matrix (DASP Top 8)\n",
    "    vuln_cols = ['Reentrancy', 'Access Control', 'Arithmetic', 'Unchecked Return Values', 'DoS', 'Bad Randomness', 'Front Running', 'Time manipulation']\n",
    "    Y = df[vuln_cols].fillna(0).astype(np.int64).values\n",
    "    \n",
    "    # 3. Heterogeneous Bipartite Edges (Contract <-> Compiler)\n",
    "    unique_compilers = df['compiler_version'].unique().tolist()\n",
    "    compiler_to_idx = {c: i for i, c in enumerate(unique_compilers)}\n",
    "    src_contract_comp = list(range(N))\n",
    "    dst_compiler = [compiler_to_idx[c] for c in df['compiler_version']]\n",
    "    edge_index_compiled_with = torch.tensor([src_contract_comp, dst_compiler], dtype=torch.long)\n",
    "    edge_index_compiles = torch.tensor([dst_compiler, src_contract_comp], dtype=torch.long)\n",
    "    \n",
    "    # 4. Semantic k-NN Graph (Contract <-> Contract)\n",
    "    nbrs = NearestNeighbors(n_neighbors=6, metric='cosine').fit(X_contracts)\n",
    "    _, indices = nbrs.kneighbors(X_contracts)\n",
    "    src_knn = [i for i in range(N) for neighbor in indices[i, 1:]]\n",
    "    dst_knn = [neighbor for i in range(N) for neighbor in indices[i, 1:]]\n",
    "    edge_index_knn = torch.tensor([src_knn, dst_knn], dtype=torch.long)\n",
    "    \n",
    "    # 5. Compiler Node Features & Train/Val/Test Split (70/15/15)\n",
    "    X_compiler_nodes = np.eye(len(unique_compilers), dtype=np.float32)\n",
    "    np.random.seed(42)\n",
    "    indices_arr = np.arange(N)\n",
    "    np.random.shuffle(indices_arr)\n",
    "    n_train = int(0.70 * N)\n",
    "    n_val = int(0.15 * N)\n",
    "    train_mask = torch.zeros(N, dtype=torch.bool)\n",
    "    val_mask = torch.zeros(N, dtype=torch.bool)\n",
    "    test_mask = torch.zeros(N, dtype=torch.bool)\n",
    "    train_mask[indices_arr[:n_train]] = True\n",
    "    val_mask[indices_arr[n_train:n_train + n_val]] = True\n",
    "    test_mask[indices_arr[n_train + n_val:]] = True\n",
    "    \n",
    "    # Assemble HeteroData Object\n",
    "    g = HeteroData()\n",
    "    g['contract'].x = torch.tensor(X_contracts, dtype=torch.float)\n",
    "    g['contract'].y = torch.tensor(Y, dtype=torch.float)\n",
    "    g['contract'].train_mask = train_mask\n",
    "    g['contract'].val_mask = val_mask\n",
    "    g['contract'].test_mask = test_mask\n",
    "    g['compiler'].x = torch.tensor(X_compiler_nodes, dtype=torch.float)\n",
    "    g['contract', 'compiled_with', 'compiler'].edge_index = edge_index_compiled_with\n",
    "    g['compiler', 'compiles', 'contract'].edge_index = edge_index_compiles\n",
    "    g['contract', 'semantic_knn', 'contract'].edge_index = edge_index_knn\n",
    "    \n",
    "    torch.save(g, graph_path)\n",
    "    print(f'Graph representation constructed and saved to {graph_path}!')\n",
    "else:\n",
    "    g = torch.load(graph_path, weights_only=False)\n",
    "\n",
    "g = g.to(device)\n",
    "print('=== HETEROGENEOUS GRAPH TOPOLOGY ===')\n",
    "print(g)\n",
    "print(f'Contract Nodes:       {g[\"contract\"].num_nodes:,} (Features: {g[\"contract\"].x.shape[1]})')\n",
    "print(f'Compiler Nodes:       {g[\"compiler\"].num_nodes:,} (Features: {g[\"compiler\"].x.shape[1]})')\n",
    "print(f'Compiled-With Edges:  {g[\"contract\", \"compiled_with\", \"compiler\"].num_edges:,}')\n",
    "print(f'Semantic k-NN Edges:  {g[\"contract\", \"semantic_knn\", \"contract\"].num_edges:,}')\n",
    "print(f'Train / Val / Test:   {g[\"contract\"].train_mask.sum().item():,} / {g[\"contract\"].val_mask.sum().item():,} / {g[\"contract\"].test_mask.sum().item():,}')\n"
]

# -----------------------------------------------------------------------------
# Cell 13: Model Training & Evaluation Trajectory (Self-Contained)
# -----------------------------------------------------------------------------
nb["cells"][13]["source"] = [
    "import json\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import f1_score, precision_score, recall_score, roc_auc_score, hamming_loss\n",
    "\n",
    "eval_file = 'data/models/eval_results.json'\n",
    "model_ckpt = 'data/models/vshgnn_best.pt'\n",
    "\n",
    "if not os.path.exists(eval_file):\n",
    "    print('Evaluation artifacts not found. Initiating VS-HGNN Training Loop (120 epochs)...')\n",
    "    os.makedirs('data/models', exist_ok=True)\n",
    "    \n",
    "    vuln_cols = ['Reentrancy', 'Access Control', 'Arithmetic', 'Unchecked Return Values', 'DoS', 'Bad Randomness', 'Front Running', 'Time manipulation']\n",
    "    num_classes = len(vuln_cols)\n",
    "    \n",
    "    # Instantiate model\n",
    "    model = VSHGNN(\n",
    "        in_channels_contract=g['contract'].x.shape[1],\n",
    "        in_channels_compiler=g['compiler'].x.shape[1],\n",
    "        hidden_dim=128,\n",
    "        out_classes=num_classes,\n",
    "        dropout=0.25\n",
    "    ).to(device)\n",
    "    \n",
    "    # Asymmetric class weighting\n",
    "    y_train = g['contract'].y[g['contract'].train_mask].cpu().numpy()\n",
    "    pos_counts = y_train.sum(axis=0)\n",
    "    total_train = len(y_train)\n",
    "    neg_counts = total_train - pos_counts\n",
    "    pos_weights = np.clip(neg_counts / (pos_counts + 1e-5), 0.5, 50.0)\n",
    "    pos_weight_tensor = torch.tensor(pos_weights, dtype=torch.float, device=device)\n",
    "    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight_tensor)\n",
    "    \n",
    "    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)\n",
    "    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=120, eta_min=1e-5)\n",
    "    \n",
    "    history = {'train_loss': [], 'val_loss': [], 'val_macro_f1': [], 'val_micro_f1': []}\n",
    "    best_val_f1 = -1.0\n",
    "    best_epoch = -1\n",
    "    \n",
    "    x_dict = g.x_dict\n",
    "    edge_index_dict = g.edge_index_dict\n",
    "    y_all = g['contract'].y\n",
    "    train_mask = g['contract'].train_mask\n",
    "    val_mask = g['contract'].val_mask\n",
    "    test_mask = g['contract'].test_mask\n",
    "    \n",
    "    for epoch in range(1, 121):\n",
    "        model.train()\n",
    "        optimizer.zero_grad()\n",
    "        logits, _ = model(x_dict, edge_index_dict)\n",
    "        loss = criterion(logits[train_mask], y_all[train_mask])\n",
    "        loss.backward()\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=2.0)\n",
    "        optimizer.step()\n",
    "        scheduler.step()\n",
    "        \n",
    "        # Validation\n",
    "        model.eval()\n",
    "        with torch.no_grad():\n",
    "            val_logits, _ = model(x_dict, edge_index_dict)\n",
    "            v_loss = criterion(val_logits[val_mask], y_all[val_mask]).item()\n",
    "            val_probs = torch.sigmoid(val_logits[val_mask]).cpu().numpy()\n",
    "            val_preds = (val_probs >= 0.5).astype(int)\n",
    "            val_targets = y_all[val_mask].cpu().numpy().astype(int)\n",
    "            val_macro = f1_score(val_targets, val_preds, average='macro', zero_division=0)\n",
    "            val_micro = f1_score(val_targets, val_preds, average='micro', zero_division=0)\n",
    "            \n",
    "        history['train_loss'].append(loss.item())\n",
    "        history['val_loss'].append(v_loss)\n",
    "        history['val_macro_f1'].append(float(val_macro))\n",
    "        history['val_micro_f1'].append(float(val_micro))\n",
    "        \n",
    "        if val_macro > best_val_f1:\n",
    "            best_val_f1 = val_macro\n",
    "            best_epoch = epoch\n",
    "            torch.save(model.state_dict(), model_ckpt)\n",
    "            \n",
    "        if epoch % 20 == 0 or epoch == 1:\n",
    "            print(f'Epoch {epoch:03d} | Train Loss: {loss.item():.4f} | Val Loss: {v_loss:.4f} | Val Macro-F1: {val_macro:.4f}')\n",
    "            \n",
    "    # Test set evaluation\n",
    "    model.load_state_dict(torch.load(model_ckpt))\n",
    "    model.eval()\n",
    "    with torch.no_grad():\n",
    "        test_logits, _ = model(x_dict, edge_index_dict)\n",
    "        test_probs = torch.sigmoid(test_logits[test_mask]).cpu().numpy()\n",
    "        test_preds = (test_probs >= 0.5).astype(int)\n",
    "        test_targets = y_all[test_mask].cpu().numpy().astype(int)\n",
    "        \n",
    "    per_class_f1 = f1_score(test_targets, test_preds, average=None, zero_division=0)\n",
    "    per_class_prec = precision_score(test_targets, test_preds, average=None, zero_division=0)\n",
    "    per_class_rec = recall_score(test_targets, test_preds, average=None, zero_division=0)\n",
    "    per_class_auc = []\n",
    "    for c in range(num_classes):\n",
    "        try:\n",
    "            per_class_auc.append(float(roc_auc_score(test_targets[:, c], test_probs[:, c])))\n",
    "        except ValueError:\n",
    "            per_class_auc.append(0.5)\n",
    "            \n",
    "    vshgnn_eval = {\n",
    "        'macro_f1': float(f1_score(test_targets, test_preds, average='macro', zero_division=0)),\n",
    "        'micro_f1': float(f1_score(test_targets, test_preds, average='micro', zero_division=0)),\n",
    "        'hamming_loss': float(hamming_loss(test_targets, test_preds)),\n",
    "        'mean_auc': float(np.mean(per_class_auc)),\n",
    "        'per_class': {}\n",
    "    }\n",
    "    for i, col in enumerate(vuln_cols):\n",
    "        vshgnn_eval['per_class'][col] = {\n",
    "            'f1': float(per_class_f1[i]),\n",
    "            'precision': float(per_class_prec[i]),\n",
    "            'recall': float(per_class_rec[i]),\n",
    "            'auc': float(per_class_auc[i]),\n",
    "            'support': int(test_targets[:, i].sum())\n",
    "        }\n",
    "        \n",
    "    # Evaluate static tools\n",
    "    benchmark_df = pd.read_csv('data/merged/vs_hgnn_supervised_benchmark.csv')\n",
    "    test_indices = np.where(test_mask.cpu().numpy())[0]\n",
    "    test_df = benchmark_df.iloc[test_indices].copy()\n",
    "    \n",
    "    tools = ['Slither', 'Mythril', 'Solhint', 'VeriSmart', 'MAIAN', 'Semgrep']\n",
    "    tool_results = {}\n",
    "    for tool in tools:\n",
    "        tool_pred_mat = np.zeros((len(test_df), num_classes), dtype=int)\n",
    "        for c_idx, col in enumerate(vuln_cols):\n",
    "            matching_cols = [c for c in test_df.columns if tool.lower() in c.lower() and (col.lower() in c.lower() or (col == 'Arithmetic' and 'overflow' in c.lower()))]\n",
    "            if matching_cols:\n",
    "                tool_pred_mat[:, c_idx] = (test_df[matching_cols].max(axis=1).fillna(0) > 0).astype(int).values\n",
    "        tool_results[tool] = {\n",
    "            'macro_f1': float(f1_score(test_targets, tool_pred_mat, average='macro', zero_division=0)),\n",
    "            'micro_f1': float(f1_score(test_targets, tool_pred_mat, average='micro', zero_division=0)),\n",
    "            'hamming_loss': float(hamming_loss(test_targets, tool_pred_mat))\n",
    "        }\n",
    "        \n",
    "    eval_data = {\n",
    "        'vshgnn': vshgnn_eval,\n",
    "        'static_tools': tool_results,\n",
    "        'best_epoch': best_epoch,\n",
    "        'history': history\n",
    "    }\n",
    "    with open(eval_file, 'w') as f:\n",
    "        json.dump(eval_data, f, indent=2)\n",
    "    print(f'Training & evaluation complete! Saved results to {eval_file}')\n",
    "else:\n",
    "    with open(eval_file, 'r') as f:\n",
    "        eval_data = json.load(f)\n",
    "\n",
    "history = eval_data['history']\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "epochs = range(1, len(history['train_loss']) + 1)\n",
    "ax1.plot(epochs, history['train_loss'], label='Train BCE Loss', color='#1f77b4', lw=2)\n",
    "ax1.plot(epochs, history['val_loss'], label='Val BCE Loss', color='#ff7f0e', lw=2, linestyle='--')\n",
    "ax1.set_title('VS-HGNN Loss Convergence Curve', fontweight='bold')\n",
    "ax1.set_xlabel('Epoch')\n",
    "ax1.set_ylabel('Weighted BCE Loss')\n",
    "ax1.legend(loc='upper right')\n",
    "ax1.grid(True, linestyle=':', alpha=0.6)\n",
    "\n",
    "ax2.plot(epochs, history['val_macro_f1'], label='Val Macro-F1', color='#2ca02c', lw=2)\n",
    "ax2.plot(epochs, history['val_micro_f1'], label='Val Micro-F1', color='#d62728', lw=2, linestyle='-.')\n",
    "best_ep = eval_data.get('best_epoch', 106)\n",
    "ax2.axvline(x=best_ep, color='purple', linestyle=':', label=f'Best Checkpoint (Epoch {best_ep})')\n",
    "ax2.set_title('Validation Performance Metric Trajectory', fontweight='bold')\n",
    "ax2.set_xlabel('Epoch')\n",
    "ax2.set_ylabel('F1 Score')\n",
    "ax2.legend(loc='lower right')\n",
    "ax2.grid(True, linestyle=':', alpha=0.6)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]

with open("vsgnn.ipynb", "w") as f:
    json.dump(nb, f, indent=1)

print("Updated vsgnn.ipynb successfully!")
